# Generated by Django 5.0 on 2023-12-26 14:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("PersonalHygieneTracker", "0002_category_user_score_alter_user_bio_routine"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="score",
        ),
        migrations.AddField(
            model_name="routine",
            name="friday",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="routine",
            name="monday",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="routine",
            name="saturday",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="routine",
            name="sunday",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="routine",
            name="thursday",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="routine",
            name="time",
            field=models.TimeField(default=datetime.time(23, 59)),
        ),
        migrations.AddField(
            model_name="routine",
            name="tuesday",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="routine",
            name="wednesday",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="badges",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="streak",
            field=models.BooleanField(null=True),
        ),
    ]
