# Generated by Django 5.0 on 2023-12-26 14:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "PersonalHygieneTracker",
            "0003_remove_user_score_routine_friday_routine_monday_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="badges",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
