# Generated by Django 5.0 on 2023-12-26 14:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("PersonalHygieneTracker", "0004_alter_user_badges"),
    ]

    operations = [
        migrations.AddField(
            model_name="routine",
            name="completed",
            field=models.BooleanField(default=False),
        ),
    ]
