# Generated by Django 5.0 on 2023-12-29 18:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("PersonalHygieneTracker", "0007_alter_routine_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="routine",
            name="friday",
        ),
        migrations.RemoveField(
            model_name="routine",
            name="monday",
        ),
        migrations.RemoveField(
            model_name="routine",
            name="saturday",
        ),
        migrations.RemoveField(
            model_name="routine",
            name="sunday",
        ),
        migrations.RemoveField(
            model_name="routine",
            name="thursday",
        ),
        migrations.RemoveField(
            model_name="routine",
            name="tuesday",
        ),
        migrations.RemoveField(
            model_name="routine",
            name="wednesday",
        ),
    ]
